"""Post-process the three C02c epsilon_K band reruns.

For each budget edge (low, central, high):
  - load tile_summary.json for metadata
  - stream draws.jsonl line-by-line (memory-efficient)
  - for PDG-passing draws: M_KK^min = (M_KK_GeV / 1000) * sqrt(max_ratio)

Compute p50 and p95 crossings in two g_s conventions:
  - perturbative: g_s ~ 1.05 (raw values)
  - strong-coupling rescaling: g_s* = 3  -> multiply by 3/1.05 = 2.857

Outputs:
  - plain-text comparison table to stdout
  - JSON summary to scan_outputs/c02c_crossings_summary.json
  - LaTeX snippet to scan_outputs/c02c_crossings_table.tex
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Optional, Sequence

import numpy as np

REPO = Path(__file__).resolve().parents[1]

GS_PERT = 1.05
GS_STAR = 3.0
GS_RESCALE = GS_STAR / GS_PERT  # ~2.857

EDGES = ("low", "central", "high")


# ── helpers ──────────────────────────────────────────────────────────

def _load_pdg_passing_mkk_min(draws_path: Path) -> np.ndarray:
    """Stream draws.jsonl and return M_KK^min (TeV) for PDG-passing draws."""
    out: list[float] = []
    with draws_path.open() as fh:
        for line in fh:
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not row.get("ok") or not row.get("passes_pdg"):
                continue
            mr = row.get("max_ratio")
            if mr is None or not np.isfinite(mr) or mr <= 0:
                continue
            mkk_tev = float(row["M_KK_GeV"]) / 1000.0
            out.append(mkk_tev * math.sqrt(float(mr)))
    return np.asarray(out)


def _load_tile_summary(run_dir: Path) -> dict:
    """Load tile_summary.json from a run directory."""
    ts = run_dir / "tile_summary.json"
    if not ts.exists():
        return {}
    with ts.open() as fh:
        return json.load(fh)


def _compute_crossings(arr: np.ndarray) -> dict:
    """Return p50/p95 crossings in both conventions, or None if empty."""
    if arr.size == 0:
        return {
            "n_pdg_pass": 0,
            "p50_pert_TeV": None,
            "p95_pert_TeV": None,
            "p50_gs_star_3_TeV": None,
            "p95_gs_star_3_TeV": None,
        }
    p50 = float(np.percentile(arr, 50))
    p95 = float(np.percentile(arr, 95))
    return {
        "n_pdg_pass": int(arr.size),
        "p50_pert_TeV": round(p50, 3),
        "p95_pert_TeV": round(p95, 3),
        "p50_gs_star_3_TeV": round(p50 * GS_RESCALE, 3),
        "p95_gs_star_3_TeV": round(p95 * GS_RESCALE, 3),
    }


def _latex_snippet(results: dict[str, dict]) -> str:
    """Generate a LaTeX table snippet for the methodology note."""
    lines = [
        r"% Auto-generated by scripts/c02c_post_process.py",
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{$M_\mathrm{KK}^{\min}$ crossings across "
        r"$\varepsilon_K$ NP-budget edges (C02c reruns).}",
        r"\label{tab:c02c_crossings}",
        r"\begin{tabular}{l r r r r r}",
        r"\hline\hline",
        r"Budget edge & $N_\mathrm{PDG}$ "
        r"& $p_{50}^\mathrm{pert}$ & $p_{95}^\mathrm{pert}$ "
        r"& $p_{50}^{g_{s*}=3}$ & $p_{95}^{g_{s*}=3}$ \\",
        r"& & [TeV] & [TeV] & [TeV] & [TeV] \\",
        r"\hline",
    ]
    for edge in EDGES:
        r = results.get(edge, {})
        if r.get("n_pdg_pass", 0) == 0:
            lines.append(
                rf"{edge} & 0 & --- & --- & --- & --- \\"
            )
        else:
            lines.append(
                rf"{edge} & {r['n_pdg_pass']:,} "
                rf"& {r['p50_pert_TeV']:.1f} & {r['p95_pert_TeV']:.1f} "
                rf"& {r['p50_gs_star_3_TeV']:.1f} "
                rf"& {r['p95_gs_star_3_TeV']:.1f} \\"
            )
    lines += [
        r"\hline\hline",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines) + "\n"


# ── main ─────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Post-process C02c epsilon_K band reruns.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--low", type=str, required=True,
        help="Path to scan_outputs dir for BUDGET_EDGE=low",
    )
    p.add_argument(
        "--central", type=str, required=True,
        help="Path to scan_outputs dir for BUDGET_EDGE=central",
    )
    p.add_argument(
        "--high", type=str, required=True,
        help="Path to scan_outputs dir for BUDGET_EDGE=high",
    )
    p.add_argument(
        "--output-dir", type=str,
        default=str(REPO / "scan_outputs"),
        help="Directory for output JSON and LaTeX (default: scan_outputs/)",
    )
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _build_parser().parse_args(argv)
    edge_dirs = {
        "low": Path(args.low),
        "central": Path(args.central),
        "high": Path(args.high),
    }
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    summary: dict = {
        "convention": {
            "g_s_pert": GS_PERT,
            "g_s_star": GS_STAR,
            "rescale_factor": round(GS_RESCALE, 4),
            "M_KK_units": "TeV",
            "M_KK_min_per_draw": "(M_KK_tile_GeV / 1000) * sqrt(max_ratio_pdg)",
        },
        "edges": {},
    }

    # Header
    print("=== C02c: M_KK^min crossings across epsilon_K budget edges (TeV) ===")
    print(f"{'edge':10s}  {'n_pdg':>10s}  "
          f"{'p50_pert':>9s} {'p95_pert':>9s}  "
          f"{'p50_gs3':>9s} {'p95_gs3':>9s}")
    print("-" * 70)

    results: dict[str, dict] = {}
    for edge in EDGES:
        rd = edge_dirs[edge]
        draws_path = rd / "draws.jsonl"

        if not draws_path.exists():
            print(f"{edge:10s}  MISSING: {draws_path}")
            results[edge] = {"error": f"draws.jsonl not found at {draws_path}"}
            continue

        # Load tile summary for metadata
        tile_meta = _load_tile_summary(rd)

        arr = _load_pdg_passing_mkk_min(draws_path)
        cx = _compute_crossings(arr)
        cx["path"] = str(rd)
        if tile_meta:
            cx["epsilon_k_budget_edge"] = tile_meta.get(
                "epsilon_k_budget_edge", edge
            )

        results[edge] = cx

        if cx["n_pdg_pass"] == 0:
            print(f"{edge:10s}  {0:>10}    "
                  f"{'--':>9s} {'--':>9s}    "
                  f"{'--':>9s} {'--':>9s}")
        else:
            print(f"{edge:10s}  {cx['n_pdg_pass']:>10,}    "
                  f"{cx['p50_pert_TeV']:>9.2f} {cx['p95_pert_TeV']:>9.2f}    "
                  f"{cx['p50_gs_star_3_TeV']:>9.2f} "
                  f"{cx['p95_gs_star_3_TeV']:>9.2f}")

    summary["edges"] = results

    # Write JSON
    json_out = output_dir / "c02c_crossings_summary.json"
    json_out.write_text(json.dumps(summary, indent=2) + "\n")
    print(f"\nJSON written to: {json_out}")

    # Write LaTeX
    tex_out = output_dir / "c02c_crossings_table.tex"
    tex_out.write_text(_latex_snippet(results))
    print(f"LaTeX written to: {tex_out}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
